Repository Catrobat/Paintroid, pull requests merged in 2019-04, with the labels that each got.

#635 PAINTROID-59: Sans Serif now default font for Texttool
  Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TextToolFontSpinnerTest.java
  Paintroid/src/main/res/values/arrays.xml
Labels: Priority: Low, Type: Bug 🐛

#638 PAINTROID-70: Prevent crash in intro
  Paintroid/src/main/java/org/catrobat/paintroid/WelcomeActivity.java
  Paintroid/src/main/java/org/catrobat/paintroid/common/MainActivityConstants.java
  Paintroid/src/main/java/org/catrobat/paintroid/contract/MainActivityContracts.java
  Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
  Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java
  Paintroid/src/main/res/values/string.xml
  Paintroid/src/test/java/org/catrobat/paintroid/test/presenter/MainActivityPresenterTest.java
  app/src/main/AndroidManifest.xml
Labels: Priority: Medium, Type: Bug 🐛

#634 PAINTROID-57: Crop/Transform Tool also works with clicks outside the Box
  Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/TransformToolIntegrationTest.java
  Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/DrawingSurfaceLocationProvider.java
  Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithRectangleShape.java
  Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TransformTool.java
Labels: Priority: Low, Type: Bug 🐛

#641 PAINTROID-19: Refactor line tool
  Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DefaultToolFactory.java
  Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/LineTool.java
Labels: Priority: Low, Type: Story 🔖

#647 PAINTROID-63: hex color input
  Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/LandscapeIntegrationTest.java
  Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/dialog/ColorDialogIntegrationTest.java
  Paintroid/src/main/java/org/catrobat/paintroid/common/Constants.java
  Paintroid/src/main/java/org/catrobat/paintroid/dialog/colorpicker/RgbSelectorView.java
  Paintroid/src/main/res/layout/color_chooser_layout_rgbview.xml
  Paintroid/src/main/res/values/colors.xml
  Paintroid/src/main/res/values/string.xml
Labels: Priority: Low, Type: Story 🔖

#643 PAINTROID-26: Refactor cursor tool
  Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/CursorToolTest.java
  Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithShape.java
  Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/CursorTool.java
  Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DefaultToolFactory.java
Labels: Priority: Low, Type: Story 🔖

#646 PAINTROID-22: Refactor text tool
  Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DefaultToolFactory.java
  Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.java
  Paintroid/src/main/java/org/catrobat/paintroid/tools/options/TextToolOptions.java
  Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultTextToolOptions.java
Labels: Priority: Low, Type: Story 🔖

#644 PAINTROID-23: Refactor import tool
  Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/ImportToolTest.java
  Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/PipetteToolTest.java
  Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/PipetteTool.java
Labels: Priority: Low, Type: Story 🔖

#645 PAINTROID-24: Refactor Tools - Fill tool
  Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/command/FillCommandTest.java
  Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/FillAlgorithmTest.java
  Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/tools/FillToolTest.java
  Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/DefaultToolFactory.java
  Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/FillTool.java
  Paintroid/src/main/java/org/catrobat/paintroid/tools/options/FillToolOptions.java
  Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultFillToolOptions.java
Labels: Priority: Low, Type: Story 🔖
